const userTypes = {
  CREATE_USER: 'CREATE_USER',
  SET_USER: 'SET_USER',
  SET_LOGGED_USER: 'SET_LOGGED_USER',
  ADD_USER_TODO: 'ADD_USER_TODO',
  SET_USER_TODO: 'SET_USER_TODO',
  EDIT_USER_TODO: 'EDIT_USER_TODO',
  SET_EDIT_USER_TODO: 'SET_EDIT_USER_TODO',
  DELETE_USER_TODO: 'DELETE_USER_TODO',
  SET_DELETE_USER_TODO: 'SET_DELETE_USER_TODO',
  FETCH_USER_DATA: 'FETCH_USER_DATA',
};

export default userTypes;
